### ISSUE TITLE
Bad result if inflextion point exists

### ISSUE THREAD

**Issue by be5invis** [fontello/cubic2quad#1] opened 2016-10-09 21:54 UTC
**upd** see https://github.com/fontello/cubic2quad/issues/1#issuecomment-252714584

`cubicToQuad(858, -113, 739, -68, 624, -31, 533, 0, 0.5)` ->

`[ 858, -113, 783.5487179487179, -84.84615384615384, 685, -51.25, 2808, -775, 533, 0 ]`

**Comment by puzrin** [comment] 2016-10-10 04:43
Could you explain details, what is wrong?

**Comment by be5invis** [comment] 2016-10-10 19:01
@puzrin 
Input:
![image](https://cloud.githubusercontent.com/assets/240091/19247410/ca890d42-8f5d-11e6-9d63-8c37aa90f97c.png)
Output:
![image](https://cloud.githubusercontent.com/assets/240091/19247404/c41cd074-8f5d-11e6-84ba-d6bc6872e95a.png)

The call, in particular, is
`cubicToQuad(858, -113, 739, -68, 624, -31, 533, 0, 0.5)`
It produces:
`[ 858,
  -113,
  783.5487179487179,
  -84.84615384615384,
  685,
  -51.25,
  2808,
  -775,
  533,
  0 ]`

**Comment by puzrin** [comment] 2016-10-10 19:15
Got it. I think you mean, that existing algorythm has no proper support for cubic curves with inflection point? That was intended assumption to simplify code and save some time. Because usually nobody has such things in fonts.

**Comment by be5invis** [comment] 2016-10-10 19:18
@puzrin However, rounding in OTFs MAY produce this for a near-straight-line input.
So, you can do something like:
1. If inflection detected but the both ends and tangents are very close to a same line -> output a line segment
2. Otherwise, split at inflection and recurse

**Comment by puzrin** [comment] 2016-10-10 19:27
I agree, it would be nice to fix, but can't promis any deadlines - busy with another projects.

**Comment by puzrin** [comment] 2016-10-26 16:42
Fixed in 1.1.0

**Closed as completed by puzrin** 2016-10-26 16:42 UTC
Labels: bug
